"""add unique constraint on holding user_stock

Revision ID: 1f7340faeebb
Revises: 2fc9fca79337
Create Date: 2026-04-12 00:49:26.018442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7340faeebb'
down_revision = '2fc9fca79337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_holding_user_stock', ['user_id', 'stock_id'])

    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_history_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_history_ticker'))

    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.drop_constraint('uq_holding_user_stock', type_='unique')

    # ### end Alembic commands ###
