"""change default time value & add unique constraint to stock history

Revision ID: 2fc9fca79337
Revises: 2f84e4e79774
Create Date: 2026-04-11 21:23:12.289885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc9fca79337'
down_revision = '2f84e4e79774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_stockhistory_ticker_date', ['ticker', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stockhistory_ticker_date', type_='unique')

    # ### end Alembic commands ###
