"""volume changed to biginteger

Revision ID: 324244ef07a0
Revises: 8a929cb99fa2
Create Date: 2026-04-12 03:33:03.452312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324244ef07a0'
down_revision = '8a929cb99fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_history', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
