"""compositive index portfolio history

Revision ID: 3edfa46f3922
Revises: 324244ef07a0
Create Date: 2026-04-21 20:12:51.551494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edfa46f3922'
down_revision = '324244ef07a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.create_index('idx_portfolio_user_date', ['user_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.drop_index('idx_portfolio_user_date')

    # ### end Alembic commands ###
