"""empty message

Revision ID: 97057c2894cb
Revises: a453a383ac9f
Create Date: 2026-04-02 21:24:10.025939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97057c2894cb'
down_revision = 'a453a383ac9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('total_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_value', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
